#!/usr/bin/env python3

import os
import sys

from analyzer import Analyzer
from termcolor import colored


def main():

    # ensure proper usage
    if len(sys.argv) != 2:
        sys.exit("Usage: ./tweets @username")

    # absolute paths to lists
    positives = os.path.join(sys.path[0], "positive-words.txt")
    negatives = os.path.join(sys.path[0], "negative-words.txt")

    # instantiate analyzer
    analyzer = Analyzer(positives, negatives)
    para, value, var1, var2, var3 = analyzer.analyze(sys.argv[1], 50)

    i = 0
    for line in para:
        if value[i] > 0.0:
            print(colored("{} {}".format(value[i], line), "green"))

        elif value[i] < 0.0:
            print(colored("{} {}".format(value[i], line), "red"))
        else:
            print(colored("{} {}".format(value[i], line), "yellow"))
        i = i + 1


if __name__ == "__main__":
    main()
